### ISSUE TITLE
Nope

### ISSUE THREAD

**Issue by NinoDLC** [prixe/lindo#18]
C:\Work\lindo\lindo [master ≡ +0 ~1 -0 !]>  npm run release:win

> lindo@2.1.4 release:win C:\Work\lindo\lindo
> build --win --x64 --ia32

  • electron-builder version=19.55.3
  • loaded configuration file=package.json ("build" field)
  • writing effective config file=releases\electron-builder.yaml
  • no native production dependencies
  • packaging       platform=win32 arch=x64 electron=1.8.2 appOutDir=releases\win-unpacked
Error: Application entry file "dist\electron\main.js" in the "C:\Work\lindo\lindo\releases\win-unpacked\resources\app.asar" does not exist. Seems like a wrong configuration.
    at error (C:\Work\lindo\lindo\node_modules\electron-builder-lib\src\asar\asarFileChecker.ts:7:12)
    at C:\Work\lindo\lindo\node_modules\electron-builder-lib\src\asar\asarFileChecker.ts:33:11
    at Generator.next (<anonymous>)
    at C:\Work\lindo\lindo\node_modules\graceful-fs\polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:155:5)
From previous event:
    at checkFileInArchive (C:\Work\lindo\lindo\node_modules\electron-builder-lib\out\asar\asarFileChecker.js:46:21)
    at C:\Work\lindo\lindo\node_modules\electron-builder-lib\src\platformPackager.ts:323:13
    at Generator.next (<anonymous>)
From previous event:
    at WinPackager.checkFileInPackage (C:\Work\lindo\lindo\node_modules\electron-builder-lib\out\platformPackager.js:408:11)
    at C:\Work\lindo\lindo\node_modules\electron-builder-lib\src\platformPackager.ts:371:16
    at Generator.next (<anonymous>)
    at C:\Work\lindo\lindo\node_modules\graceful-fs\polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:155:5)
From previous event:
    at WinPackager.sanityCheckPackage (C:\Work\lindo\lindo\node_modules\electron-builder-lib\out\platformPackager.js:426:11)
    at C:\Work\lindo\lindo\node_modules\electron-builder-lib\src\platformPackager.ts:213:16
    at Generator.next (<anonymous>)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
From previous event:
    at WinPackager.doPack (C:\Work\lindo\lindo\node_modules\electron-builder-lib\out\platformPackager.js:284:11)
    at C:\Work\lindo\lindo\node_modules\electron-builder-lib\src\platformPackager.ts:114:16
    at Generator.next (<anonymous>)
From previous event:
    at WinPackager.pack (C:\Work\lindo\lindo\node_modules\electron-builder-lib\out\platformPackager.js:202:11)
    at C:\Work\lindo\lindo\node_modules\electron-builder-lib\src\packager.ts:364:24
    at Generator.next (<anonymous>)
    at xfs.stat (C:\Work\lindo\lindo\node_modules\fs-extra-p\node_modules\fs-extra\lib\mkdirs\mkdirs.js:56:16)
    at C:\Work\lindo\lindo\node_modules\graceful-fs\polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:155:5)
From previous event:
    at Packager.doBuild (C:\Work\lindo\lindo\node_modules\electron-builder-lib\out\packager.js:432:11)
    at C:\Work\lindo\lindo\node_modules\electron-builder-lib\src\packager.ts:308:52
    at Generator.next (<anonymous>)
    at C:\Work\lindo\lindo\node_modules\graceful-fs\graceful-fs.js:99:16
    at C:\Work\lindo\lindo\node_modules\graceful-fs\graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:141:20)
From previous event:
    at Packager._build (C:\Work\lindo\lindo\node_modules\electron-builder-lib\out\packager.js:376:11)
    at C:\Work\lindo\lindo\node_modules\electron-builder-lib\src\packager.ts:270:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
From previous event:
    at Packager.build (C:\Work\lindo\lindo\node_modules\electron-builder-lib\out\packager.js:332:11)
    at C:\Work\lindo\lindo\node_modules\electron-builder\src\builder.ts:310:40
    at Generator.next (<anonymous>)
From previous event:
    at _build (C:\Work\lindo\lindo\node_modules\electron-builder\out\builder.js:61:21)
    at build (C:\Work\lindo\lindo\node_modules\electron-builder\src\builder.ts:280:10)
    at then (C:\Work\lindo\lindo\node_modules\electron-builder\src\cli\cli.ts:48:33)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
From previous event:
    at Object.args [as handler] (C:\Work\lindo\lindo\node_modules\electron-builder\src\cli\cli.ts:48:33)
    at Object.runCommand (C:\Work\lindo\lindo\node_modules\electron-builder\node_modules\yargs\lib\command.js:235:44)
    at Object.parseArgs [as _parseArgs] (C:\Work\lindo\lindo\node_modules\electron-builder\node_modules\yargs\yargs.js:1074:24)
    at Object.get [as argv] (C:\Work\lindo\lindo\node_modules\electron-builder\node_modules\yargs\yargs.js:989:21)
    at Object.<anonymous> (C:\Work\lindo\lindo\node_modules\electron-builder\src\cli\cli.ts:42:15)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)

**Comment by Clover-Lindo** [comment]
I'm surely too late, but here's my answer anyway:
You have to run `npm run build` before `npm run release:win` to build sources before generating the release files. This is why `dist\electron\main.js` doesn't exist.
