### ISSUE TITLE
Error launching app: Unable to find Electron app

### ISSUE THREAD

**Issue by p2635** [prixe/lindo#23]
I tried to install this on Kubuntu 18.04 but got the below errors:

````
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@6.6.0
3 info using node@v10.15.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle lindo@2.2.0~prestart: lindo@2.2.0
6 info lifecycle lindo@2.2.0~start: lindo@2.2.0
7 verbose lifecycle lindo@2.2.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle lindo@2.2.0~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/seru/Apps/lindo/node_modules/.bin:/home/seru/gems/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle lindo@2.2.0~start: CWD: /home/seru/Apps/lindo
10 silly lifecycle lindo@2.2.0~start: Args: [ '-c', 'electron ./' ]
11 silly lifecycle lindo@2.2.0~start: Returned: code: 1  signal: null
12 info lifecycle lindo@2.2.0~start: Failed to exec start script
13 verbose stack Error: lindo@2.2.0 start: `electron ./`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:962:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
14 verbose pkgid lindo@2.2.0
15 verbose cwd /home/seru/Apps/lindo
16 verbose Linux 4.15.0-43-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
18 verbose node v10.15.0
19 verbose npm  v6.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error lindo@2.2.0 start: `electron ./`
22 error Exit status 1
23 error Failed at the lindo@2.2.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by p2635** [comment]
Sorry I missed this part '$ npm run build:dev'
